version: "3.3"

services:
  
  server:
    build: .
    hostname: iam-server
    container_name: iam-server
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    links:
      - database
    depends_on:
      - database
    environment:
      DB_DRIVER: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  database:
    image: mariadb:latest
    hostname: iam-database
    container_name: iam-database
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  database:
