POST http://localhost:8000/api/auth/register
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "secret" }

###

POST http://localhost:8000/api/auth/login
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "secret" }

###

POST http://localhost:8000/api/auth/refresh
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "UcBkpBRwKsAlN55E5WAGGyseivnaiSjv" }

###

POST http://localhost:8000/api/auth/logout
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "UcBkpBRwKsAlN55E5WAGGyseivnaiSjv" }



