# @name apiTest

GET http://localhost:8000/api/noodles
Accept: text/plain
Cache-Control: no-cache

### 

# @name register
POST http://localhost:8000/api/auth/register
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "secret" }

###

# @name loginSuccess
POST http://localhost:8000/api/auth/login
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "secret" }


###

# @name loginFailure
POST http://localhost:8000/api/auth/login
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "definitelynotthesecret" }

###

@refreshToken = {{loginSuccess.response.body.$.token}}

# @name refreshSuccess
POST http://localhost:8000/api/auth/refresh
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "{{refreshToken}}" }


###

@refreshToken = {{loginSuccess.response.body.$.token}}

# @name logoutSuccess
POST http://localhost:8000/api/auth/logout
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "{{refreshToken}}" }


###

@accessToken = {{refreshSuccess.response.body.$.access}}

# @name adminFailed
GET http://localhost:8000/api/admin/noodles
Accept: text/plain
Cache-Control: no-cache

###

@accessToken = {{refreshSuccess.response.body.$.access}}

# @name adminSuccess
GET http://localhost:8000/api/admin/noodles
Accept: text/plain
Cache-Control: no-cache
Authorization: Bearer {{accessToken}}
