openapi: 3.0.0
info:
  title: IAM
  version: '1.0'
  contact:
    name: Groupe de Fer
    email: info@groupedefer.be
    url: unanimity.be
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  description: Use trash bin fill ratio information within a city to improve a basic citizen service.
servers:
  - url: 'http://localhost:3000'
paths:
  '/can/{id}/sync':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: ''
      tags:
        - can
      operationId: post-sync-can-id
      responses:
        '200':
          description: OK
        '406':
          description: Not acceptable
      description: 'upload information concerning the {id} trash can'
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: The id of the trash can
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                signature:
                  type: string
                data:
                  $ref: '#/components/schemas/TrashBinForm'
        description: ''
  /cans:
    get:
      summary: Your GET endpoint
      tags:
        - admin
        - can
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                uniqueItems: false
                items:
                  $ref: '#/components/schemas/TrashBin'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrashBin'
              examples:
                example-1:
                  value:
                    - id: string
                      longitude: 0
                      latitude: 0
                      public_key: string
      operationId: get-admin-cans
      description: Get all trash can information
    parameters: []
  /login:
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Unauthorized
      description: send the login form to complete login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      tags:
        - user
  '/admin/can/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: put-admin-can-id
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      description: Update a trash bin
      security:
        - Tokenauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrashBin'
      tags:
        - admin
        - can
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: The id of the trash bin
    delete:
      summary: ''
      operationId: delete-admin-can-id
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not found
      security:
        - Tokenauth: []
      description: Delete an existing trash bin
      tags:
        - admin
        - tag
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: The id of the trash bin
  /admin/can:
    post:
      summary: ''
      operationId: post-admin-can
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
        '401':
          description: Unauthorized
      description: Create a new trash bin
      security:
        - Tokenauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrashBin'
      tags:
        - admin
        - can
  '/can/{id}/info':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - can
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrashBinInfo'
      operationId: get-can-id-info
      description: Get all the available information about one trash bin
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: The id of the trash bin
components:
  schemas:
    TrashBin:
      title: TrashBin
      type: object
      description: TrashBin information
      properties:
        id:
          type: string
        longitude:
          type: number
        latitude:
          type: number
        public_key:
          type: string
      required:
        - id
        - public_key
    TrashBinForm:
      title: TrashBinData
      type: object
      properties:
        id:
          type: string
        time:
          type: string
        filling_rate:
          type: number
      required:
        - id
        - time
        - filling_rate
    Credentials:
      title: Login
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    TrashBinInfo:
      title: TrashBinInfo
      type: object
      properties:
        trash_bin:
          $ref: '#/components/schemas/TrashBin'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Data'
    Data:
      title: Data
      type: object
      properties:
        time:
          type: string
        filling_rate:
          type: number
      required:
        - time
        - filling_rate
  securitySchemes:
    Tokenauth:
      name: auth_token
      type: apiKey
      in: cookie
      description: Authentication token
tags:
  - name: can
  - name: admin
  - name: user
  - name: tag
