# @name apiTest

GET http://localhost:8000/api/noodles
Accept: text/plain
Cache-Control: no-cache

### ----------------------------------------------------------------- REGISTER

# @name register
POST http://localhost:8000/api/auth/register
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "secret" }


### ------------------------------------------------------------ LOGIN SUCCESS

# @name loginSuccess
POST http://localhost:8000/api/auth/login
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "secret" }


### ------------------------------------------------------------ LOGIN FAILURE

# @name loginFailure
POST http://localhost:8000/api/auth/login
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "password": "definitelynotthesecret" }


### ---------------------------------------------------------- REFRESH SUCCESS

@refreshToken = {{loginSuccess.response.body.$.token}}

# @name refreshSuccess
POST http://localhost:8000/api/auth/refresh
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "{{refreshToken}}" }

### ----------------------------------------------- CONSECUTIVE REFRESH SUCCESS

@consecutiveRefreshToken = {{refreshSuccess.response.body.$.refresh}}

# @name consecutiveRefreshSuccess
POST http://localhost:8000/api/auth/refresh
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "{{consecutiveRefreshToken}}" }


### ---------------------------------------------------------- REFRESH FAILURE

# @name refreshFailure
POST http://localhost:8000/api/auth/refresh
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "whatever" }


### ----------------------------------------------------------- LOGOUT SUCCESS

@logoutRefreshToken = {{consecutiveRefreshSuccess.response.body.$.refresh}}

# @name logoutSuccess
POST http://localhost:8000/api/auth/logout
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "{{logoutRefreshToken}}" }


### ----------------------------------------------------------- LOGOUT FAILURE

# @name logoutFailure
POST http://localhost:8000/api/auth/logout
Accept: application/json
Cache-Control: no-cache

{ "username": "john", "token": "whatever" }


### ------------------------------------------------------------ ADMIN SUCCESS

@accessToken = {{consecutiveRefreshSuccess.response.body.$.access}}

# @name adminSuccess
GET http://localhost:8000/api/admin/noodles
Accept: text/plain
Cache-Control: no-cache
Authorization: Bearer {{accessToken}}


### ------------------------------------------------------------ ADMIN FAILURE

# @name adminFailure
GET http://localhost:8000/api/admin/noodles
Accept: text/plain
Cache-Control: no-cache


### --------------------------------------------------------------------- CANS

# @name cans
GET http://localhost:8000/api/cans
Accept: text/plain
Cache-Control: no-cache


### ----------------------------------------------------------------- THAT CAN

# @name can
GET http://localhost:8000/api/can/abc
Accept: text/plain
Cache-Control: no-cache
